# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-21 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_pen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.AddField(
            model_name='application',
            name='authorization_grant_type',
            field=models.CharField(choices=[('authorization-code', 'Authorization code'), ('implicit', 'Implicit'), ('password', 'Resource owner password-based'), ('client-credentials', 'Client credentials')], default='password', max_length=50, verbose_name='授权类型'),
        ),
        migrations.AddField(
            model_name='application',
            name='client_name',
            field=models.CharField(default='', max_length=255, verbose_name='客户端名称'),
        ),
        migrations.AddField(
            model_name='application',
            name='client_secret',
            field=models.CharField(default='TODO', max_length=255, verbose_name='客户端密钥'),
        ),
        migrations.AddField(
            model_name='application',
            name='client_type',
            field=models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], default='confidential', max_length=20, verbose_name='客户端类型'),
        ),
        migrations.AddField(
            model_name='application',
            name='redirect_uris',
            field=models.CharField(blank=True, max_length=255, verbose_name='TODO 授权成功回调地址（implicit/authorization-code 模式必填写）'),
        ),
        migrations.AddField(
            model_name='application',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='客户端说明'),
        ),
        migrations.AddField(
            model_name='application',
            name='skip_authorization',
            field=models.BooleanField(default=False, verbose_name='TODO 是否跳过授权'),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_id',
            field=models.CharField(default='TODO', max_length=100, primary_key=True, serialize=False, verbose_name='客户端唯一标识'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user_id',
            field=models.CharField(db_index=True, default=0, max_length=20, verbose_name='创建人ID'),
        ),
    ]
